--- # local action demo
- hosts: remote
  user: test
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
   - name: Ping application server before we run our install
     local_action: command ping -c5 shaurya23096.mylabserver.com
   - name: Install lynx on emote server
     yum: pkg=lynx state=latest
