--- # mysql_user module demo
- hosts: host
  user: test
  become: yes
  connection: ssh
  tasks:
   - name: install the mysql python support library 
     yum: pkg=MySQL-python state=latest
   - name: Create a new user calld BOB and give him all access
     mysql_user: name=bob password=123  priv=*.*:ALL state=present login_user=root login_password=password123
