--- # pause model 

- hosts: remote
  become: yes
  user: test
  connection: ssh
  gather_facts: no
  tasks:
   - name: install httpd
     action: yum name=httpd state=installed
   - name: pausing
     pause:
       seconds: 3 
   - name: verify lynx installation
     action: yum name=lynx state=present
     

