--- # service example
- hosts: remote
  user: test
  become: yes
  connection: ssh
  gather_facts: yes
  tasks:
    - name: install Web Server
      action: yum name=httpd state=installed
    - name: start the web server
      service: name=httpd state=started
    - name: Enable HTTPD After Reboot
      service: name=httpd enabled=yes
