--- # example for setfacts
- hosts: remote
  user: test
  become: yes
  connection: ssh
  gather_facts: no
  vars:
   playbook_version: 0.1
  tasks:
   - name: Local variable display
     set_fact: 
       singlefact: something
   - debug:
       msg: '{{ playbook_version }}'
   - debug:
       msg: '{{ singlefact }}'
