--- # start at playbook exaple
- hosts: remote
  user: test
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
   - name: Install telnet
     yum: pkg=telnet state=latest
   - name: Install lynx
     yum: pkg=lynx state=latest
   - name: List Home
     command: ls -al /home/test
     register: result
   - debug: var=result 
